[[types]]
name = "boolean"
documentation = """
This is a boolean value that is read with `DataInputStream#readBoolean()`
"""

[[types]]
name = "float"
documentation = """
This is a float value that is read with `DataInputStream#readFloat()`
"""

[[types]]
name = "utf"
documentation = """
This is a UTF string that is read with `DataInputStream#readUTF()`
"""